name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install -r requirements.txt; fi
    
    - name: Check code formatting with black
      run: |
        black --check agent_manager tests

    - name: Lint with ruff
      run: |
        ruff check agent_manager tests
    
    - name: Type check with mypy
      run: |
        mypy agent_manager
    
    - name: Run tests
      run: |
        pytest tests/ --cov=agent_manager --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and export
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: agent-manager:test
        outputs: type=docker,dest=/tmp/agent-manager-image.tar
    
    - name: Test Docker image
      run: |
        docker load --input /tmp/agent-manager-image.tar
        docker run --rm agent-manager:test python -m pytest -xvs agent_manager/tests/